# These are supported funding model platforms

github: yourusername # Replace with your GitHub Sponsors username
patreon: yourpatreonusername # Replace with your Patreon username
open_collective: yourcollectiveusername # Replace with your Open Collective username
ko_fi: yourkofiusername # Replace with your Ko-fi username
tide: yourtideusername # Replace with your Tide username
community_bridge: yourcommunitybridgeusername # Replace with your Community Bridge username
liberapay: yourliberapayusername # Replace with your Liberapay username
issuehunt: yourissuehuntusername # Replace with your IssueHunt username
otechie: yourotechieusername # Replace with your Otechie username
custom: ['https://your-custom-donation-link.com'] # Replace with your custom donation link
